import Head from "next/head";
import { Flex } from "@chakra-ui/react";
import NavBar from "@/components/layout/NavBar";
import AppLayout from "@/components/layout/AppLayout";

export default function Home() {
  return (
    <>
      <Head>
        <title>hi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout></AppLayout>
    </>
  );
}
